version: '3'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "3101:3101"
    volumes:
      - ./loki.conf:/etc/nginx/conf.d/default.conf:ro
  loki:
    image: grafana/loki:2.9.2
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml:ro
  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    user: "1000"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana